---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-html-pv
spec:
  storageClassName: "standardrw"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: nginx-html-pvc
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/[YOUR_PROJECT_ID]/zones/[YOUR_ZONE]/disks/[YOUR_DISK_NAME] # or /regions/[YOUR_REGION]/...
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: nginx-html-pvc
spec:
  storageClassName: "standardro"
  volumeName: nginx-html-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi