steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello-1
  - --region=europe-west3
  - --source=.
  - --trigger-http
  - --runtime=nodejs22
  - --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY