steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello-1
  - --region=europe-west3
  - --trigger-http
  - --runtime=nodejs22
  - --entry-point=helloHttp
  - --allow-unauthenticated
  - --source=google-cloud/cloud-run-functions-cloud-build/
options:
  logging: CLOUD_LOGGING_ONLY
