---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multi
  labels:
    app: nginx-multi
spec:
  selector:
    matchLabels:
      app: nginx-multi
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: nginx-multi
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: documentroot
      - image: alpine:latest
        name: alpine
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        volumeMounts:
          - mountPath: /mnt
            name: documentroot
      volumes:
      - name: documentroot
        persistentVolumeClaim:
          claimName: nginx-filestore-html-pvc